### ISSUE TITLE
Periodically recheck url's in the open space directory

### ISSUE THREAD

**Issue by ghost** [SpaceApi-archive/SpaceApi#10]
Ideally, url's are rechecked periodically, and if they fail to validate the owners should be notified (perhaps give them a chance to fix the error within a certain period before being removed from the directory).

**Comment by slopjong** [comment]
That's on my roadmap since I'm working on the lint tool. Please let's synchronize if you are working on it. I want to avoid that we both work on the same problem. As the lint tool and its directory are in a good almost ready state the rechecker is my next thing scheduled for the weekend or next week.

**Comment by ghost** [comment]
Nope, i'm not working on anything atm spaceapi wise..

**Comment by slopjong** [comment]
Done.
