### ISSUE TITLE
Our Hackspace is no longer listed in the directory

### ISSUE THREAD

**Issue by sre** [SpaceApi-archive/SpaceApi#49]
The Mainframe hackspace has been removed from the directory, but cannot be added either ("The space is already in the directory.").

URL: http://status.mainframe.io/api/spaceInfo

**Comment by slopjong** [comment]
I don't know why your endpoint has disappeared again from the public list. I checked the git log and it happened after September 30th.

Please keep me up-to-date if your endpoint disappears again. There must be a bug somewhere but I don't know yet what exactly is broken.

Should I use your new URL?

**Comment by slopjong** [comment]
@sre github says that your comment was posted one month ago. Was this (maybe 1 day) before September 1st?

On September 1st I must have changed your URL.

```
Date:   Sun Sep 1 23:33:01 2013 +0200
Change request: Mainframe
```

**Comment by sre** [comment]
Yes, I reported this bug before you updated the URL. But the old URL should have worked also. I guess there's a bug in handling HTTP redirects.

Currently the only strange thing is, that our space is listed as v12 in the directory. The validator validates 0.13.

**Comment by slopjong** [comment]
This is because of the cache. The validator shows all the versions to which your implementation validates no matter what you define in the api field. The website however is displaying the version from the api field of your cached json.

**Comment by sre** [comment]
Then maybe you should update the cached json regularly? Otherwise it doesn't make much sense to display them IMHO.

**Comment by slopjong** [comment]
Actually it's updating regularly - once a day. The directory worked good so far and has been very reliable for over 18 months already. Mostly things go wrong because of the endpoints themselves such as misconfiguration of the DNS, broken syntax or for other reasons that the endpoint maintainers didn't care much about.

**Comment by sre** [comment]
Our endpoint uses space-api 0.13 exclusively since the url change, so the cached data is at least 5 weeks old. Running the validator by hand works and outputs "Your JSON is compliant to the specs 0.13".

**Comment by slopjong** [comment]
I know that it's compliant to specs 0.13.

I could imagine that you were one of the spaces that I asked to look after their endpoint. If you didn't reply within a week you might be one of those that got removed from the crons to increase the performance.

I posted about 12 spaces causing trouble which means that they were absolutely unuseable (syntax errors, not reachable at all for days/weeks, php/ruby warnings thrown, forbidden status code). If you were one of those then it's simply actio reactio ;-)

**Comment by slopjong** [comment]
I know the reason now. It's because you renamed your space. If a space's name is changed I should always be noticed explicitly. This affects the directory because the system only trusts known spaces, this means the space name you used on your submission is kept. So the issue is no bug but caused by your space itself then.

I'll fix it tonight.

**Comment by slopjong** [comment]
I've just fixed it.

**Comment by sre** [comment]
thanks
