### ISSUE TITLE
Using the new directory?

### ISSUE THREAD

**Issue by slopjong** [SpaceApi-archive/SpaceApi#9]
I've implemented a directory where people can add themselves their space API JSON if it's missing. First it's validated against the specs and if the validation fails it's not added. It seems to be a bit strict but in my opinion it's the only way to get unified JSONs that are compatible with every space app.

The directory includes a filter mechanism by using a Lisp-like syntax. Check http://openspace.slopjong.de and click on 'Directory'.

@sonologic are you ok with using the new directory instead of yours? It's not my intention to take over the world but to improve it ;-)

**Comment by ghost** [comment]
Absolutely ok with that, as it has been my intention to do it like that from the start :)

I can set up a cronjob pulling your directory in its entirety for people still using the chasmcity url.

Also, if you check the git repos, I implemented a ?fmt=a option on request of someone, which returns the directory as an array of spaces, instead of as a single object with fieldnames for the space names (which requires you to use object introspection if you parse the json strictly into an object). To be compatible, the new directory should support this parameter as well.

**Comment by lhw** [comment]
That certain someone was also me. If you don't want to include the other format I can probably live with it. Parsing the directory with a few loops would be okay. As long as the actual spacestatus json is neatly formed.

**Comment by slopjong** [comment]
@sonologic you could do a redirect to http://openspace.slopjong.de/directory.json There are some spaces that are not 100% valid against one specs version at least. I'll add them manually and notify them to correct them to be valid.

@lhw I'll implement the fmt option, no problem. With "neatly formed" you surely mean a not compressed JSON which is more human-readable.

**Comment by lhw** [comment]
No thats not what I meant. I meant the changes I proposed for 0.13, which you already adopted in your lintian check. Before we had only a loose concept of how sensors should be defined, the way it is now is much easier to parse into a static structure.

@slopjong I noticed that you have a tiny mistake on your directory page. The barometer in your example has to be an object and not an array. Otherwise good job and I will change the link in my android widget to your directory with the next version.

**Comment by slopjong** [comment]
The fmt option isn't yet implemented, I've cooked in the meantime and I still need to clean up my repository before I continue to mess around ;-)

Thanks to point the "mistake" out. I just wanted to show how the keys of the nested structure of the associative array are encoded to be a valid filter but people might think it's an example how to implement their json.

Edit: according to the specification sensors is an array of arrays so my example is ok.

**Comment by lhw** [comment]
The next version of the widget isn't due for another 1-2 weeks. So no rush.

**Comment by ghost** [comment]
I'll put in the redirect when the fmt option is there, so we don't break things. Also, i'll add the new spaces I added recently to the new directory.

**Comment by slopjong** [comment]
Already done, I mean the new spaces are already added not the fmt option.

**Comment by slopjong** [comment]
@sonologic fmt added. I'll be offline for the rest of this day, cu next days.

**Comment by ghost** [comment]
redirect activated

**Comment by slopjong** [comment]
ACE Monster Toys added their JSON to the directory. I'm happy that the tool works as it should and that people are served without any latency :-)

**Comment by ghost** [comment]
What's up with the validator and directory? Validator errors out, directory is gone????

**Comment by slopjong** [comment]
Uhm, when did it happen exactly? I didn't notice anything. What time and how long?

**Comment by ghost** [comment]
Seems to be when i use chrome to view the page.. Bug with chrome? Both on macosx and linux, the directory fails w/ chrome.

**Comment by slopjong** [comment]
I have no problem with chromium 18.0.1025.168 (Developer Build 0 Linux) except one minor thing which has nothing to do with the directory itself.

I wonder that you have problems with the directory which is a simple json. This is what I get:

```
Request URL:http://openspace.slopjong.de/directory.json
Request Method:GET
Status Code:200 OK
```

Request Headers:

```
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Charset:ISO-8859-1,utf-8;q=0.7,*;q=0.3
Accept-Encoding:gzip,deflate,sdch
Accept-Language:en-US,en;q=0.8
Connection:keep-alive
Host:openspace.slopjong.de
User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.168 Safari/535.19
```

Response Headers:

```
Access-Control-Allow-Origin:*
Connection:close
Content-Type:application/json
Date:Tue, 15 May 2012 18:33:39 GMT
Server:Apache
Transfer-Encoding:chunked
```
